# Generated by Django 4.2.6 on 2023-10-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_alter_kitob_muallif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kutubxonachi',
            name='ish_vaqti',
            field=models.CharField(choices=[('06:00 dan 12:00 gacha', '06:00 dan 12:00 gacha'), ('12:00 dan 18:00 gacha', '12:00 dan 18:00 gacha'), ('18:00 dan 23:59 gacha', '18:00 dan 23:59 gacha')], max_length=255),
        ),
    ]
